<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2.3 Exercises | Introduction to Statistical Learning Using R Book Club</title>
  <meta name="description" content="This is the product of the R4DS Online Learning Community’s Introduction to Statistical Learning Using R Book Club." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="2.3 Exercises | Introduction to Statistical Learning Using R Book Club" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the product of the R4DS Online Learning Community’s Introduction to Statistical Learning Using R Book Club." />
  <meta name="github-repo" content="r4ds/bookclub-islr" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.3 Exercises | Introduction to Statistical Learning Using R Book Club" />
  
  <meta name="twitter:description" content="This is the product of the R4DS Online Learning Community’s Introduction to Statistical Learning Using R Book Club." />
  

<meta name="author" content="The R4DS Online Learning Community" />


<meta name="date" content="2022-03-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="assessing-model-accuracy.html"/>
<link rel="next" href="meeting-videos-1.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Statistical Learning Using R Book Club</a></li>

<li class="divider"></li>
<li><a href="index.html#welcome">Welcome<span></span></a><ul>
<li><a href="book-club-meetings.html#book-club-meetings">Book club meetings<span></span></a></li>
<li><a href="st-edition-vs-2nd-edition.html#st-edition-vs-2nd-edition">1st edition vs 2nd edition<span></span></a></li>
<li><a href="pace.html#pace">Pace<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction<span></span></a><ul>
<li class="chapter" data-level="1.1" data-path="what-is-statistical-learning.html"><a href="what-is-statistical-learning.html"><i class="fa fa-check"></i><b>1.1</b> What is statistical learning?<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="why-islr.html"><a href="why-islr.html"><i class="fa fa-check"></i><b>1.2</b> Why ISLR?<span></span></a></li>
<li class="chapter" data-level="1.3" data-path="notation.html"><a href="notation.html"><i class="fa fa-check"></i><b>1.3</b> Notation<span></span></a></li>
<li class="chapter" data-level="1.4" data-path="what-have-we-gotten-ourselves-into.html"><a href="what-have-we-gotten-ourselves-into.html"><i class="fa fa-check"></i><b>1.4</b> What have we gotten ourselves into?<span></span></a></li>
<li class="chapter" data-level="1.5" data-path="wheres-the-data.html"><a href="wheres-the-data.html"><i class="fa fa-check"></i><b>1.5</b> Where’s the data?<span></span></a></li>
<li class="chapter" data-level="1.6" data-path="some-useful-resources.html"><a href="some-useful-resources.html"><i class="fa fa-check"></i><b>1.6</b> Some useful resources:<span></span></a></li>
<li class="chapter" data-level="1.7" data-path="what-is-covered-in-the-book.html"><a href="what-is-covered-in-the-book.html"><i class="fa fa-check"></i><b>1.7</b> What is covered in the book?<span></span></a></li>
<li class="chapter" data-level="1.8" data-path="how-is-the-book-divided.html"><a href="how-is-the-book-divided.html"><i class="fa fa-check"></i><b>1.8</b> How is the book divided?<span></span></a></li>
<li class="chapter" data-level="1.9" data-path="some-examples-of-the-problems-addressed-with-statistical-analysis.html"><a href="some-examples-of-the-problems-addressed-with-statistical-analysis.html"><i class="fa fa-check"></i><b>1.9</b> Some examples of the problems addressed with statistical analysis<span></span></a></li>
<li class="chapter" data-level="1.10" data-path="datasets-provided-in-the-islr2-package.html"><a href="datasets-provided-in-the-islr2-package.html"><i class="fa fa-check"></i><b>1.10</b> Datasets provided in the ISLR2 package<span></span></a><ul>
<li class="chapter" data-level="1.10.1" data-path="datasets-provided-in-the-islr2-package.html"><a href="datasets-provided-in-the-islr2-package.html#example-datasets"><i class="fa fa-check"></i><b>1.10.1</b> Example datasets<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="meeting-videos.html"><a href="meeting-videos.html"><i class="fa fa-check"></i><b>1.11</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="1.11.1" data-path="meeting-videos.html"><a href="meeting-videos.html#cohort-1"><i class="fa fa-check"></i><b>1.11.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="1.11.2" data-path="meeting-videos.html"><a href="meeting-videos.html#cohort-2"><i class="fa fa-check"></i><b>1.11.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="1.11.3" data-path="meeting-videos.html"><a href="meeting-videos.html#cohort-3"><i class="fa fa-check"></i><b>1.11.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="learning.html"><a href="learning.html"><i class="fa fa-check"></i><b>2</b> Statistical Learning<span></span></a><ul>
<li class="chapter" data-level="2.1" data-path="what-is-statistical-learning-1.html"><a href="what-is-statistical-learning-1.html"><i class="fa fa-check"></i><b>2.1</b> What is Statistical Learning?<span></span></a><ul>
<li class="chapter" data-level="2.1.1" data-path="what-is-statistical-learning-1.html"><a href="what-is-statistical-learning-1.html#why-estimate-f"><i class="fa fa-check"></i><b>2.1.1</b> Why Estimate <span class="math inline">\(f\)</span>?<span></span></a></li>
<li class="chapter" data-level="2.1.2" data-path="what-is-statistical-learning-1.html"><a href="what-is-statistical-learning-1.html#how-do-we-estimate-f"><i class="fa fa-check"></i><b>2.1.2</b> How do we estimate <span class="math inline">\(f\)</span>?<span></span></a></li>
<li class="chapter" data-level="2.1.3" data-path="what-is-statistical-learning-1.html"><a href="what-is-statistical-learning-1.html#prediction-accuracy-vs-model-interpretability"><i class="fa fa-check"></i><b>2.1.3</b> Prediction Accuracy vs Model Interpretability<span></span></a></li>
<li class="chapter" data-level="2.1.4" data-path="what-is-statistical-learning-1.html"><a href="what-is-statistical-learning-1.html#supervised-versus-unsupervised-learning"><i class="fa fa-check"></i><b>2.1.4</b> Supervised Versus Unsupervised Learning<span></span></a></li>
<li class="chapter" data-level="2.1.5" data-path="what-is-statistical-learning-1.html"><a href="what-is-statistical-learning-1.html#regression-versus-classification-problems"><i class="fa fa-check"></i><b>2.1.5</b> Regression Versus Classification Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="assessing-model-accuracy.html"><a href="assessing-model-accuracy.html"><i class="fa fa-check"></i><b>2.2</b> Assessing Model Accuracy<span></span></a><ul>
<li class="chapter" data-level="2.2.1" data-path="assessing-model-accuracy.html"><a href="assessing-model-accuracy.html#measuring-quality-of-fit"><i class="fa fa-check"></i><b>2.2.1</b> Measuring Quality of Fit<span></span></a></li>
<li class="chapter" data-level="2.2.2" data-path="assessing-model-accuracy.html"><a href="assessing-model-accuracy.html#the-bias-variance-trade-off"><i class="fa fa-check"></i><b>2.2.2</b> The Bias-Variance Trade-Off<span></span></a></li>
<li class="chapter" data-level="2.2.3" data-path="assessing-model-accuracy.html"><a href="assessing-model-accuracy.html#the-classification-setting"><i class="fa fa-check"></i><b>2.2.3</b> The Classification Setting<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="exercises.html"><a href="exercises.html"><i class="fa fa-check"></i><b>2.3</b> Exercises<span></span></a></li>
<li class="chapter" data-level="2.4" data-path="meeting-videos-1.html"><a href="meeting-videos-1.html"><i class="fa fa-check"></i><b>2.4</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="2.4.1" data-path="meeting-videos-1.html"><a href="meeting-videos-1.html#cohort-1-1"><i class="fa fa-check"></i><b>2.4.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="2.4.2" data-path="meeting-videos-1.html"><a href="meeting-videos-1.html#cohort-2-1"><i class="fa fa-check"></i><b>2.4.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="2.4.3" data-path="meeting-videos-1.html"><a href="meeting-videos-1.html#cohort-3-1"><i class="fa fa-check"></i><b>2.4.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="linear.html"><a href="linear.html"><i class="fa fa-check"></i><b>3</b> Linear Regression<span></span></a><ul>
<li class="chapter" data-level="3.1" data-path="questions-to-answer.html"><a href="questions-to-answer.html"><i class="fa fa-check"></i><b>3.1</b> Questions to Answer<span></span></a></li>
<li class="chapter" data-level="3.2" data-path="simple-linear-regression-definition.html"><a href="simple-linear-regression-definition.html"><i class="fa fa-check"></i><b>3.2</b> Simple Linear Regression: Definition<span></span></a></li>
<li class="chapter" data-level="3.3" data-path="simple-linear-regression-visualization.html"><a href="simple-linear-regression-visualization.html"><i class="fa fa-check"></i><b>3.3</b> Simple Linear Regression: Visualization<span></span></a></li>
<li class="chapter" data-level="3.4" data-path="simple-linear-regression-math.html"><a href="simple-linear-regression-math.html"><i class="fa fa-check"></i><b>3.4</b> Simple Linear Regression: Math<span></span></a><ul>
<li class="chapter" data-level="3.4.1" data-path="simple-linear-regression-math.html"><a href="simple-linear-regression-math.html#visualization-of-fit"><i class="fa fa-check"></i><b>3.4.1</b> Visualization of Fit<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="assessing-accuracy-of-coefficient-estimates.html"><a href="assessing-accuracy-of-coefficient-estimates.html"><i class="fa fa-check"></i><b>3.5</b> Assessing Accuracy of Coefficient Estimates<span></span></a></li>
<li class="chapter" data-level="3.6" data-path="meeting-videos-2.html"><a href="meeting-videos-2.html"><i class="fa fa-check"></i><b>3.6</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="3.6.1" data-path="meeting-videos-2.html"><a href="meeting-videos-2.html#cohort-1-2"><i class="fa fa-check"></i><b>3.6.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="3.6.2" data-path="meeting-videos-2.html"><a href="meeting-videos-2.html#cohort-2-2"><i class="fa fa-check"></i><b>3.6.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="3.6.3" data-path="meeting-videos-2.html"><a href="meeting-videos-2.html#cohort-3-2"><i class="fa fa-check"></i><b>3.6.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>4</b> Classification<span></span></a><ul>
<li class="chapter" data-level="4.1" data-path="an-overview-of-classification.html"><a href="an-overview-of-classification.html"><i class="fa fa-check"></i><b>4.1</b> An Overview of Classification<span></span></a></li>
<li class="chapter" data-level="4.2" data-path="why-not-linear-regression.html"><a href="why-not-linear-regression.html"><i class="fa fa-check"></i><b>4.2</b> Why NOT Linear Regression?<span></span></a></li>
<li class="chapter" data-level="4.3" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>4.3</b> Logistic Regression<span></span></a><ul>
<li class="chapter" data-level="4.3.1" data-path="logistic-regression.html"><a href="logistic-regression.html#multiple-logistic-regression"><i class="fa fa-check"></i><b>4.3.1</b> Multiple Logistic Regression<span></span></a></li>
<li class="chapter" data-level="4.3.2" data-path="logistic-regression.html"><a href="logistic-regression.html#multinomial-logistic-regression"><i class="fa fa-check"></i><b>4.3.2</b> Multinomial Logistic Regression<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="generative-models-for-classification.html"><a href="generative-models-for-classification.html"><i class="fa fa-check"></i><b>4.4</b> Generative Models for Classification<span></span></a></li>
<li class="chapter" data-level="4.5" data-path="a-comparison-of-classification-methods.html"><a href="a-comparison-of-classification-methods.html"><i class="fa fa-check"></i><b>4.5</b> A Comparison of Classification Methods<span></span></a><ul>
<li class="chapter" data-level="4.5.1" data-path="a-comparison-of-classification-methods.html"><a href="a-comparison-of-classification-methods.html#linear-discriminant-analysis-for-p-1"><i class="fa fa-check"></i><b>4.5.1</b> Linear Discriminant Analysis for p = 1<span></span></a></li>
<li class="chapter" data-level="4.5.2" data-path="a-comparison-of-classification-methods.html"><a href="a-comparison-of-classification-methods.html#linear-discriminant-analysis-for-p-1-1"><i class="fa fa-check"></i><b>4.5.2</b> Linear Discriminant Analysis for p &gt; 1<span></span></a></li>
<li class="chapter" data-level="4.5.3" data-path="a-comparison-of-classification-methods.html"><a href="a-comparison-of-classification-methods.html#quadratic-discriminant-analysis-qda"><i class="fa fa-check"></i><b>4.5.3</b> Quadratic Discriminant Analysis (QDA)<span></span></a></li>
<li class="chapter" data-level="4.5.4" data-path="a-comparison-of-classification-methods.html"><a href="a-comparison-of-classification-methods.html#naive-bayes"><i class="fa fa-check"></i><b>4.5.4</b> Naive Bayes<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="summary-of-the-classification-methods.html"><a href="summary-of-the-classification-methods.html"><i class="fa fa-check"></i><b>4.6</b> Summary of the classification methods<span></span></a><ul>
<li class="chapter" data-level="4.6.1" data-path="summary-of-the-classification-methods.html"><a href="summary-of-the-classification-methods.html#an-analytical-comparison"><i class="fa fa-check"></i><b>4.6.1</b> An Analytical Comparison<span></span></a></li>
<li class="chapter" data-level="4.6.2" data-path="summary-of-the-classification-methods.html"><a href="summary-of-the-classification-methods.html#an-empirical-comparison"><i class="fa fa-check"></i><b>4.6.2</b> An Empirical Comparison<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>4.7</b> Generalized Linear Models<span></span></a></li>
<li class="chapter" data-level="4.8" data-path="linear-regression-with-count-data---negative-values.html"><a href="linear-regression-with-count-data---negative-values.html"><i class="fa fa-check"></i><b>4.8</b> Linear regression with count data - negative values<span></span></a></li>
<li class="chapter" data-level="4.9" data-path="linear-regression-with-count-data---heteroscedasticity.html"><a href="linear-regression-with-count-data---heteroscedasticity.html"><i class="fa fa-check"></i><b>4.9</b> Linear regression with count data - heteroscedasticity<span></span></a></li>
<li class="chapter" data-level="4.10" data-path="problems-with-linear-regression-of-count-data.html"><a href="problems-with-linear-regression-of-count-data.html"><i class="fa fa-check"></i><b>4.10</b> Problems with linear regression of count data<span></span></a></li>
<li class="chapter" data-level="4.11" data-path="poisson-distribution.html"><a href="poisson-distribution.html"><i class="fa fa-check"></i><b>4.11</b> Poisson distribution<span></span></a></li>
<li class="chapter" data-level="4.12" data-path="poisson-regression-model-mean-lambda.html"><a href="poisson-regression-model-mean-lambda.html"><i class="fa fa-check"></i><b>4.12</b> Poisson Regression Model mean (lambda)<span></span></a></li>
<li class="chapter" data-level="4.13" data-path="estimating-the-poisson-regression-parameters.html"><a href="estimating-the-poisson-regression-parameters.html"><i class="fa fa-check"></i><b>4.13</b> Estimating the Poisson Regression parameters<span></span></a></li>
<li class="chapter" data-level="4.14" data-path="interpreting-poisson-regression.html"><a href="interpreting-poisson-regression.html"><i class="fa fa-check"></i><b>4.14</b> Interpreting Poisson Regression<span></span></a></li>
<li class="chapter" data-level="4.15" data-path="advantages-of-poisson-regression.html"><a href="advantages-of-poisson-regression.html"><i class="fa fa-check"></i><b>4.15</b> Advantages of Poisson Regression<span></span></a></li>
<li class="chapter" data-level="4.16" data-path="generalized-linear-models-1.html"><a href="generalized-linear-models-1.html"><i class="fa fa-check"></i><b>4.16</b> Generalized Linear Models<span></span></a></li>
<li class="chapter" data-level="4.17" data-path="addendum---logistic-regression-assumptions.html"><a href="addendum---logistic-regression-assumptions.html"><i class="fa fa-check"></i><b>4.17</b> Addendum - Logistic Regression Assumptions<span></span></a></li>
<li class="chapter" data-level="4.18" data-path="lab-classification-methods.html"><a href="lab-classification-methods.html"><i class="fa fa-check"></i><b>4.18</b> Lab: Classification Methods<span></span></a></li>
<li class="chapter" data-level="4.19" data-path="meeting-videos-3.html"><a href="meeting-videos-3.html"><i class="fa fa-check"></i><b>4.19</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="4.19.1" data-path="meeting-videos-3.html"><a href="meeting-videos-3.html#cohort-1-3"><i class="fa fa-check"></i><b>4.19.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="4.19.2" data-path="meeting-videos-3.html"><a href="meeting-videos-3.html#cohort-2-3"><i class="fa fa-check"></i><b>4.19.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="4.19.3" data-path="meeting-videos-3.html"><a href="meeting-videos-3.html#cohort-3-3"><i class="fa fa-check"></i><b>4.19.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="resampling-methods.html"><a href="resampling-methods.html"><i class="fa fa-check"></i><b>5</b> Resampling Methods<span></span></a><ul>
<li class="chapter" data-level="5.1" data-path="validation-set-approach.html"><a href="validation-set-approach.html"><i class="fa fa-check"></i><b>5.1</b> Validation Set Approach<span></span></a></li>
<li class="chapter" data-level="5.2" data-path="validation-error-rate-varies-depending-on-data-set.html"><a href="validation-error-rate-varies-depending-on-data-set.html"><i class="fa fa-check"></i><b>5.2</b> Validation Error Rate Varies Depending on Data Set<span></span></a></li>
<li class="chapter" data-level="5.3" data-path="leave-one-out-cross-validation-loocv.html"><a href="leave-one-out-cross-validation-loocv.html"><i class="fa fa-check"></i><b>5.3</b> Leave-One-Out Cross-Validation (LOOCV)<span></span></a></li>
<li class="chapter" data-level="5.4" data-path="advantages-of-loocv-over-validation-set-approach.html"><a href="advantages-of-loocv-over-validation-set-approach.html"><i class="fa fa-check"></i><b>5.4</b> Advantages of LOOCV over Validation Set Approach<span></span></a></li>
<li class="chapter" data-level="5.5" data-path="k-fold-cross-validation.html"><a href="k-fold-cross-validation.html"><i class="fa fa-check"></i><b>5.5</b> k-fold Cross-Validation<span></span></a></li>
<li class="chapter" data-level="5.6" data-path="graphical-illustration-of-k-fold-approach.html"><a href="graphical-illustration-of-k-fold-approach.html"><i class="fa fa-check"></i><b>5.6</b> Graphical Illustration of k-fold Approach<span></span></a></li>
<li class="chapter" data-level="5.7" data-path="advantages-of-k-fold-cross-validation-over-loocv.html"><a href="advantages-of-k-fold-cross-validation-over-loocv.html"><i class="fa fa-check"></i><b>5.7</b> Advantages of k-fold Cross-Validation over LOOCV<span></span></a></li>
<li class="chapter" data-level="5.8" data-path="bias-variance-tradeoff-and-k-fold-cross-validation.html"><a href="bias-variance-tradeoff-and-k-fold-cross-validation.html"><i class="fa fa-check"></i><b>5.8</b> Bias-Variance Tradeoff and k-fold Cross-Validation<span></span></a></li>
<li class="chapter" data-level="5.9" data-path="cross-validation-on-classification-problems.html"><a href="cross-validation-on-classification-problems.html"><i class="fa fa-check"></i><b>5.9</b> Cross-Validation on Classification Problems<span></span></a></li>
<li class="chapter" data-level="5.10" data-path="logistic-polynomial-regression-bayes-decision-boundaries-and-k-fold-cross-validation.html"><a href="logistic-polynomial-regression-bayes-decision-boundaries-and-k-fold-cross-validation.html"><i class="fa fa-check"></i><b>5.10</b> Logistic Polynomial Regression, Bayes Decision Boundaries, and k-fold Cross Validation<span></span></a></li>
<li class="chapter" data-level="5.11" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>5.11</b> The Bootstrap<span></span></a></li>
<li class="chapter" data-level="5.12" data-path="population-distribution-compared-to-bootstrap-distribution.html"><a href="population-distribution-compared-to-bootstrap-distribution.html"><i class="fa fa-check"></i><b>5.12</b> Population Distribution Compared to Bootstrap Distribution<span></span></a></li>
<li class="chapter" data-level="5.13" data-path="bootstrap-standard-error.html"><a href="bootstrap-standard-error.html"><i class="fa fa-check"></i><b>5.13</b> Bootstrap Standard Error<span></span></a></li>
<li class="chapter" data-level="5.14" data-path="lab-cross-validation-and-the-bootstrap.html"><a href="lab-cross-validation-and-the-bootstrap.html"><i class="fa fa-check"></i><b>5.14</b> Lab: Cross-Validation and the Bootstrap<span></span></a><ul>
<li class="chapter" data-level="5.14.1" data-path="lab-cross-validation-and-the-bootstrap.html"><a href="lab-cross-validation-and-the-bootstrap.html#the-validation-set-approach"><i class="fa fa-check"></i><b>5.14.1</b> The Validation Set Approach<span></span></a></li>
<li class="chapter" data-level="5.14.2" data-path="lab-cross-validation-and-the-bootstrap.html"><a href="lab-cross-validation-and-the-bootstrap.html#leave-one-out-cross-validation"><i class="fa fa-check"></i><b>5.14.2</b> Leave-One-Out Cross-Validation<span></span></a></li>
<li class="chapter" data-level="5.14.3" data-path="lab-cross-validation-and-the-bootstrap.html"><a href="lab-cross-validation-and-the-bootstrap.html#k-fold-cross-validation-1"><i class="fa fa-check"></i><b>5.14.3</b> k-Fold Cross-Validation<span></span></a></li>
<li class="chapter" data-level="5.14.4" data-path="lab-cross-validation-and-the-bootstrap.html"><a href="lab-cross-validation-and-the-bootstrap.html#the-bootstrap-1"><i class="fa fa-check"></i><b>5.14.4</b> The Bootstrap<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.15" data-path="meeting-videos-4.html"><a href="meeting-videos-4.html"><i class="fa fa-check"></i><b>5.15</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="5.15.1" data-path="meeting-videos-4.html"><a href="meeting-videos-4.html#cohort-1-4"><i class="fa fa-check"></i><b>5.15.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="5.15.2" data-path="meeting-videos-4.html"><a href="meeting-videos-4.html#cohort-2-4"><i class="fa fa-check"></i><b>5.15.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="5.15.3" data-path="meeting-videos-4.html"><a href="meeting-videos-4.html#cohort-3-4"><i class="fa fa-check"></i><b>5.15.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html"><i class="fa fa-check"></i><b>6</b> Linear Model Selection and Regularization<span></span></a><ul>
<li class="chapter" data-level="6.1" data-path="subset-selection.html"><a href="subset-selection.html"><i class="fa fa-check"></i><b>6.1</b> Subset Selection<span></span></a></li>
<li><a href="context-for-this-chapter.html#context-for-this-chapter">Context for This Chapter<span></span></a></li>
<li><a href="best-subset-selection-bss.html#best-subset-selection-bss">Best Subset Selection (BSS)<span></span></a></li>
<li><a href="bss-algorithm.html#bss-algorithm">BSS Algorithm<span></span></a></li>
<li><a href="bss-algorithm-1.html#bss-algorithm-1">BSS Algorithm<span></span></a></li>
<li><a href="behind-the-dots-bssing-islr2credit.html#behind-the-dots-bssing-islr2credit">Behind the dots, BSS’ing ISLR2::Credit<span></span></a></li>
<li><a href="best-subset-selection-bss-1.html#best-subset-selection-bss-1">Best Subset Selection (BSS)<span></span></a></li>
<li><a href="forward-stepwise-subset-selection-fsss.html#forward-stepwise-subset-selection-fsss">Forward Stepwise Subset Selection (FsSS)<span></span></a></li>
<li><a href="fsssing-islr2credit.html#fsssing-islr2credit">FsSS’ing ISLR2::Credit<span></span></a></li>
<li><a href="backward-stepwise-subset-selection-bsss.html#backward-stepwise-subset-selection-bsss">Backward Stepwise Subset Selection (BsSS)<span></span></a></li>
<li><a href="guided-searches.html#guided-searches">“Guided” searches<span></span></a></li>
<li><a href="choosing-the-best-model.html#choosing-the-best-model">Choosing the best model<span></span></a></li>
<li><a href="adjustment-methods.html#adjustment-methods">Adjustment Methods<span></span></a></li>
<li><a href="avoiding-adjustment-methods.html#avoiding-adjustment-methods">Avoiding Adjustment Methods<span></span></a></li>
<li><a href="various-variable-selection-methods-on-islr2credit.html#various-variable-selection-methods-on-islr2credit">Various variable selection methods on ISLR2::Credit<span></span></a></li>
<li><a href="in-conclusion.html#in-conclusion">In conclusion…<span></span></a></li>
<li class="chapter" data-level="6.2" data-path="shrinkage-methods.html"><a href="shrinkage-methods.html"><i class="fa fa-check"></i><b>6.2</b> Shrinkage Methods<span></span></a></li>
<li><a href="overview.html#overview">Overview<span></span></a></li>
<li><a href="ols-review.html#ols-review">OLS review<span></span></a></li>
<li><a href="ridge-regression.html#ridge-regression">Ridge Regression<span></span></a></li>
<li><a href="ridge-regression-visually.html#ridge-regression-visually">Ridge Regression, Visually<span></span></a></li>
<li><a href="ridge-good.html#ridge-good">Ridge, good?<span></span></a></li>
<li><a href="preprocessing.html#preprocessing">Preprocessing<span></span></a></li>
<li><a href="the-lasso.html#the-lasso">The Lasso<span></span></a></li>
<li><a href="justin-grimmer-homework.html#justin-grimmer-homework">Justin Grimmer Homework<span></span></a></li>
<li><a href="visualization-of-such-that-formulations.html#visualization-of-such-that-formulations">Visualization of “such that” formulations<span></span></a></li>
<li><a href="bayesian-interpretation.html#bayesian-interpretation">Bayesian Interpretation<span></span></a></li>
<li><a href="bayesian-interpretation-cont.html#bayesian-interpretation-cont">Bayesian Interpretation (cont)<span></span></a></li>
<li><a href="choosing-the-tuning-parameter.html#choosing-the-tuning-parameter">Choosing the tuning parameter<span></span></a></li>
<li><a href="tuning-lambda.html#tuning-lambda">Tuning <span class="math inline">\(\lambda\)</span><span></span></a></li>
<li class="chapter" data-level="6.3" data-path="dimension-reduction-methods.html"><a href="dimension-reduction-methods.html"><i class="fa fa-check"></i><b>6.3</b> Dimension Reduction Methods<span></span></a></li>
<li><a href="the-math.html#the-math">The Math<span></span></a></li>
<li><a href="principal-components-regression.html#principal-components-regression">Principal Components Regression<span></span></a></li>
<li><a href="principal-components-regression-1.html#principal-components-regression-1">Principal Components Regression<span></span></a></li>
<li><a href="principal-components-regression-2.html#principal-components-regression-2">Principal Components Regression<span></span></a></li>
<li><a href="principal-components-regression-3.html#principal-components-regression-3">Principal Components Regression<span></span></a></li>
<li><a href="principal-components-regression-4.html#principal-components-regression-4">Principal Components Regression<span></span></a></li>
<li><a href="principal-components-regression-5.html#principal-components-regression-5">Principal Components Regression<span></span></a></li>
<li><a href="partial-least-squares.html#partial-least-squares">Partial Least Squares<span></span></a></li>
<li class="chapter" data-level="6.4" data-path="considerations-in-high-dimensions.html"><a href="considerations-in-high-dimensions.html"><i class="fa fa-check"></i><b>6.4</b> Considerations in High Dimensions<span></span></a></li>
<li><a href="considerations-in-high-dimensions-1.html#considerations-in-high-dimensions-1">Considerations in High Dimensions<span></span></a></li>
<li><a href="lasso-etc-vs-dimensionality.html#lasso-etc-vs-dimensionality">Lasso (etc) vs Dimensionality<span></span></a></li>
<li class="chapter" data-level="6.5" data-path="meeting-videos-5.html"><a href="meeting-videos-5.html"><i class="fa fa-check"></i><b>6.5</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="6.5.1" data-path="meeting-videos-5.html"><a href="meeting-videos-5.html#cohort-1-5"><i class="fa fa-check"></i><b>6.5.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="6.5.2" data-path="meeting-videos-5.html"><a href="meeting-videos-5.html#cohort-2-5"><i class="fa fa-check"></i><b>6.5.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="6.5.3" data-path="meeting-videos-5.html"><a href="meeting-videos-5.html#cohort-3-5"><i class="fa fa-check"></i><b>6.5.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html"><i class="fa fa-check"></i><b>7</b> Moving Beyond Linearity<span></span></a><ul>
<li class="chapter" data-level="7.1" data-path="polynomial-and-step-regression.html"><a href="polynomial-and-step-regression.html"><i class="fa fa-check"></i><b>7.1</b> Polynomial and Step Regression<span></span></a></li>
<li class="chapter" data-level="7.2" data-path="splines.html"><a href="splines.html"><i class="fa fa-check"></i><b>7.2</b> Splines<span></span></a></li>
<li class="chapter" data-level="7.3" data-path="generalized-additive-models.html"><a href="generalized-additive-models.html"><i class="fa fa-check"></i><b>7.3</b> Generalized Additive Models<span></span></a></li>
<li class="chapter" data-level="7.4" data-path="meeting-videos-6.html"><a href="meeting-videos-6.html"><i class="fa fa-check"></i><b>7.4</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="7.4.1" data-path="meeting-videos-6.html"><a href="meeting-videos-6.html#cohort-1-6"><i class="fa fa-check"></i><b>7.4.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="7.4.2" data-path="meeting-videos-6.html"><a href="meeting-videos-6.html#cohort-2-6"><i class="fa fa-check"></i><b>7.4.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="7.4.3" data-path="meeting-videos-6.html"><a href="meeting-videos-6.html#cohort-3-6"><i class="fa fa-check"></i><b>7.4.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tree-based-methods.html"><a href="tree-based-methods.html"><i class="fa fa-check"></i><b>8</b> Tree-Based Methods<span></span></a><ul>
<li class="chapter" data-level="8.1" data-path="slide-1.html"><a href="slide-1.html"><i class="fa fa-check"></i><b>8.1</b> Slide 1<span></span></a></li>
<li class="chapter" data-level="8.2" data-path="slide-2.html"><a href="slide-2.html"><i class="fa fa-check"></i><b>8.2</b> Slide 2<span></span></a></li>
<li class="chapter" data-level="8.3" data-path="meeting-videos-7.html"><a href="meeting-videos-7.html"><i class="fa fa-check"></i><b>8.3</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="8.3.1" data-path="meeting-videos-7.html"><a href="meeting-videos-7.html#cohort-1-7"><i class="fa fa-check"></i><b>8.3.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="8.3.2" data-path="meeting-videos-7.html"><a href="meeting-videos-7.html#cohort-2-7"><i class="fa fa-check"></i><b>8.3.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="8.3.3" data-path="meeting-videos-7.html"><a href="meeting-videos-7.html#cohort-3-7"><i class="fa fa-check"></i><b>8.3.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="support-vector-machines.html"><a href="support-vector-machines.html"><i class="fa fa-check"></i><b>9</b> Support Vector Machines<span></span></a><ul>
<li class="chapter" data-level="9.1" data-path="maximal-margin-classifier-hyperplanes.html"><a href="maximal-margin-classifier-hyperplanes.html"><i class="fa fa-check"></i><b>9.1</b> Maximal Margin Classifier &amp; Hyperplanes<span></span></a></li>
<li class="chapter" data-level="9.2" data-path="using-a-separating-hyperplane-to-classify.html"><a href="using-a-separating-hyperplane-to-classify.html"><i class="fa fa-check"></i><b>9.2</b> Using a Separating Hyperplane to Classify<span></span></a></li>
<li class="chapter" data-level="9.3" data-path="visual-example-of-using-a-hyperplane-to-classify.html"><a href="visual-example-of-using-a-hyperplane-to-classify.html"><i class="fa fa-check"></i><b>9.3</b> Visual Example of Using a Hyperplane to Classify<span></span></a></li>
<li class="chapter" data-level="9.4" data-path="maximal-margin-classifier.html"><a href="maximal-margin-classifier.html"><i class="fa fa-check"></i><b>9.4</b> Maximal Margin Classifier<span></span></a></li>
<li class="chapter" data-level="9.5" data-path="visual-representation-of-maximal-margin-classifier.html"><a href="visual-representation-of-maximal-margin-classifier.html"><i class="fa fa-check"></i><b>9.5</b> Visual Representation of Maximal Margin Classifier<span></span></a></li>
<li class="chapter" data-level="9.6" data-path="mathematics-of-the-mmc.html"><a href="mathematics-of-the-mmc.html"><i class="fa fa-check"></i><b>9.6</b> Mathematics of the MMC<span></span></a></li>
<li class="chapter" data-level="9.7" data-path="support-vector-classifiers.html"><a href="support-vector-classifiers.html"><i class="fa fa-check"></i><b>9.7</b> Support Vector Classifiers<span></span></a></li>
<li class="chapter" data-level="9.8" data-path="mathematics-of-the-svc.html"><a href="mathematics-of-the-svc.html"><i class="fa fa-check"></i><b>9.8</b> Mathematics of the SVC<span></span></a></li>
<li class="chapter" data-level="9.9" data-path="visual-illustration-of-svc.html"><a href="visual-illustration-of-svc.html"><i class="fa fa-check"></i><b>9.9</b> Visual Illustration of SVC<span></span></a></li>
<li class="chapter" data-level="9.10" data-path="support-vector-machines-1.html"><a href="support-vector-machines-1.html"><i class="fa fa-check"></i><b>9.10</b> Support Vector Machines<span></span></a></li>
<li class="chapter" data-level="9.11" data-path="support-vector-machines-cont..html"><a href="support-vector-machines-cont..html"><i class="fa fa-check"></i><b>9.11</b> Support Vector Machines, cont.<span></span></a></li>
<li class="chapter" data-level="9.12" data-path="radial-kernels.html"><a href="radial-kernels.html"><i class="fa fa-check"></i><b>9.12</b> Radial Kernels<span></span></a></li>
<li class="chapter" data-level="9.13" data-path="radial-kernels-cont..html"><a href="radial-kernels-cont..html"><i class="fa fa-check"></i><b>9.13</b> Radial Kernels, cont.<span></span></a></li>
<li class="chapter" data-level="9.14" data-path="svms-with-more-than-two-classes.html"><a href="svms-with-more-than-two-classes.html"><i class="fa fa-check"></i><b>9.14</b> SVMs with More than Two Classes<span></span></a></li>
<li class="chapter" data-level="9.15" data-path="lab-support-vector-classifier.html"><a href="lab-support-vector-classifier.html"><i class="fa fa-check"></i><b>9.15</b> Lab: Support Vector Classifier<span></span></a><ul>
<li class="chapter" data-level="9.15.1" data-path="lab-support-vector-classifier.html"><a href="lab-support-vector-classifier.html#tuning"><i class="fa fa-check"></i><b>9.15.1</b> Tuning<span></span></a></li>
<li class="chapter" data-level="9.15.2" data-path="lab-support-vector-classifier.html"><a href="lab-support-vector-classifier.html#linearly-separable-data"><i class="fa fa-check"></i><b>9.15.2</b> Linearly separable data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.16" data-path="lab-support-vector-machine-non-linear-kernel.html"><a href="lab-support-vector-machine-non-linear-kernel.html"><i class="fa fa-check"></i><b>9.16</b> Lab: Support Vector Machine (non-linear kernel)<span></span></a></li>
<li class="chapter" data-level="9.17" data-path="meeting-videos-8.html"><a href="meeting-videos-8.html"><i class="fa fa-check"></i><b>9.17</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="9.17.1" data-path="meeting-videos-8.html"><a href="meeting-videos-8.html#cohort-1-8"><i class="fa fa-check"></i><b>9.17.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="9.17.2" data-path="meeting-videos-8.html"><a href="meeting-videos-8.html#cohort-2-8"><i class="fa fa-check"></i><b>9.17.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="9.17.3" data-path="meeting-videos-8.html"><a href="meeting-videos-8.html#cohort-3-8"><i class="fa fa-check"></i><b>9.17.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="deep-learning.html"><a href="deep-learning.html"><i class="fa fa-check"></i><b>10</b> Deep Learning<span></span></a><ul>
<li class="chapter" data-level="10.1" data-path="slide-1-1.html"><a href="slide-1-1.html"><i class="fa fa-check"></i><b>10.1</b> Slide 1<span></span></a></li>
<li class="chapter" data-level="10.2" data-path="slide-2-1.html"><a href="slide-2-1.html"><i class="fa fa-check"></i><b>10.2</b> Slide 2<span></span></a></li>
<li class="chapter" data-level="10.3" data-path="meeting-videos-9.html"><a href="meeting-videos-9.html"><i class="fa fa-check"></i><b>10.3</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="10.3.1" data-path="meeting-videos-9.html"><a href="meeting-videos-9.html#cohort-1-9"><i class="fa fa-check"></i><b>10.3.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="10.3.2" data-path="meeting-videos-9.html"><a href="meeting-videos-9.html#cohort-2-9"><i class="fa fa-check"></i><b>10.3.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="10.3.3" data-path="meeting-videos-9.html"><a href="meeting-videos-9.html#cohort-3-9"><i class="fa fa-check"></i><b>10.3.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html"><i class="fa fa-check"></i><b>11</b> Survival Analysis and Censored Data<span></span></a><ul>
<li class="chapter" data-level="11.1" data-path="slide-1-2.html"><a href="slide-1-2.html"><i class="fa fa-check"></i><b>11.1</b> Slide 1<span></span></a></li>
<li class="chapter" data-level="11.2" data-path="slide-2-2.html"><a href="slide-2-2.html"><i class="fa fa-check"></i><b>11.2</b> Slide 2<span></span></a></li>
<li class="chapter" data-level="11.3" data-path="meeting-videos-10.html"><a href="meeting-videos-10.html"><i class="fa fa-check"></i><b>11.3</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="11.3.1" data-path="meeting-videos-10.html"><a href="meeting-videos-10.html#cohort-1-10"><i class="fa fa-check"></i><b>11.3.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="11.3.2" data-path="meeting-videos-10.html"><a href="meeting-videos-10.html#cohort-2-10"><i class="fa fa-check"></i><b>11.3.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="11.3.3" data-path="meeting-videos-10.html"><a href="meeting-videos-10.html#cohort-3-10"><i class="fa fa-check"></i><b>11.3.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html"><i class="fa fa-check"></i><b>12</b> Unsupervised Learning<span></span></a><ul>
<li class="chapter" data-level="12.1" data-path="slide-1-3.html"><a href="slide-1-3.html"><i class="fa fa-check"></i><b>12.1</b> Slide 1<span></span></a></li>
<li class="chapter" data-level="12.2" data-path="slide-2-3.html"><a href="slide-2-3.html"><i class="fa fa-check"></i><b>12.2</b> Slide 2<span></span></a></li>
<li class="chapter" data-level="12.3" data-path="meeting-videos-11.html"><a href="meeting-videos-11.html"><i class="fa fa-check"></i><b>12.3</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="12.3.1" data-path="meeting-videos-11.html"><a href="meeting-videos-11.html#cohort-1-11"><i class="fa fa-check"></i><b>12.3.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="12.3.2" data-path="meeting-videos-11.html"><a href="meeting-videos-11.html#cohort-2-11"><i class="fa fa-check"></i><b>12.3.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="12.3.3" data-path="meeting-videos-11.html"><a href="meeting-videos-11.html#cohort-3-11"><i class="fa fa-check"></i><b>12.3.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="multiple-testing.html"><a href="multiple-testing.html"><i class="fa fa-check"></i><b>13</b> Multiple Testing<span></span></a><ul>
<li class="chapter" data-level="13.1" data-path="slide-1-4.html"><a href="slide-1-4.html"><i class="fa fa-check"></i><b>13.1</b> Slide 1<span></span></a></li>
<li class="chapter" data-level="13.2" data-path="slide-2-4.html"><a href="slide-2-4.html"><i class="fa fa-check"></i><b>13.2</b> Slide 2<span></span></a></li>
<li class="chapter" data-level="13.3" data-path="meeting-videos-12.html"><a href="meeting-videos-12.html"><i class="fa fa-check"></i><b>13.3</b> Meeting Videos<span></span></a><ul>
<li class="chapter" data-level="13.3.1" data-path="meeting-videos-12.html"><a href="meeting-videos-12.html#cohort-1-12"><i class="fa fa-check"></i><b>13.3.1</b> Cohort 1<span></span></a></li>
<li class="chapter" data-level="13.3.2" data-path="meeting-videos-12.html"><a href="meeting-videos-12.html#cohort-2-12"><i class="fa fa-check"></i><b>13.3.2</b> Cohort 2<span></span></a></li>
<li class="chapter" data-level="13.3.3" data-path="meeting-videos-12.html"><a href="meeting-videos-12.html#cohort-3-12"><i class="fa fa-check"></i><b>13.3.3</b> Cohort 3<span></span></a></li>
</ul></li>
</ul></li>
<li><a href="abbreviations.html#abbreviations">Abbreviations<span></span></a></li>
<li><a href="latex.html#latex">Appendix: Bookdown and LaTeX Notes<span></span></a><ul>
<li><a href="markdown-highlighting.html#markdown-highlighting">Markdown highlighting<span></span></a></li>
<li><a href="text-coloring.html#text-coloring">Text coloring<span></span></a></li>
<li><a href="x99-4.html#x99-4">Section references<span></span></a></li>
<li><a href="footnotes.html#footnotes">Footnotes<span></span></a></li>
<li><a href="formatting-text.html#formatting-text">Formatting Text<span></span></a></li>
<li><a href="figures.html#figures">Figures<span></span></a></li>
<li><a href="displaying-formula.html#displaying-formula">Displaying Formula<span></span></a><ul>
<li><a href="displaying-formula.html#formatting">Formatting<span></span></a></li>
<li><a href="displaying-formula.html#symbols">Symbols<span></span></a></li>
<li><a href="displaying-formula.html#notation-1">Notation<span></span></a></li>
</ul></li>
<li><a href="equations.html#equations">Equations<span></span></a><ul>
<li><a href="equations.html#basic-equation">Basic Equation<span></span></a></li>
<li><a href="equations.html#case-when-equation-large-curly-brace">Case-When Equation (Large Curly Brace)<span></span></a></li>
<li><a href="equations.html#alligned-with-underbars">Alligned with Underbars<span></span></a></li>
</ul></li>
<li><a href="greek-letters.html#greek-letters">Greek letters<span></span></a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistical Learning Using R Book Club</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exercises" class="section level2 hasAnchor">
<h2><span class="header-section-number">2.3</span> Exercises<a href="exercises.html#exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<h4>
<strong>Conceptual</strong>
</h4>
<p><span style="color: red;">
1. For each of parts (a) through (d), indicate whether we would generally expect the performance of a flexible statistical learning method to be better or worse than an inflexible method. Justify your answer.</span></p>
<p><span style="color: red;">
(a) The sample size n is extremely large, and the number of predictors p is small.</span></p>
<p>A flexible model can take advantage of the large number of observations to make a detailed model.</p>
<p><span style="color: red;">
(b) The number of predictors p is extremely large, and the number
of observations n is small.</span></p>
<p>I’d apply Principal Component Analysis to drive p well under n, and then an inflexible, parametric method like Ordinary Least Squares could provide a model with a reasonable test set performance.</p>
<p><span style="color: red;">
(c) The relationship between the predictors and response is highly
non-linear.</span></p>
<p>A flexible model could better capture the non-linearity.</p>
<p><span style="color: red;">
(d) The variance of the error terms, i.e. σ2 = Var(ϵ), is extremely
high.</span></p>
<p>An inflexible, parametric method would provide a standardized, average slice across the domain.</p>
<p><span style="color: red;">
2. Explain whether each scenario is a classification or regression problem, and indicate whether we are most interested in inference or prediction. Finally, provide n and p.</span></p>
<p><span style="color: red;">
(a) We collect a set of data on the top 500 firms in the US. For each
firm we record profit, number of employees, industry and the
CEO salary. We are interested in understanding which factors
affect CEO salary.</span></p>
<p>The problem is a regression, and we are interested in inferring the component factors. N is 500, and p is 3.</p>
<p><span style="color: red;">
(b) We are considering launching a new product and wish to know
whether it will be a success or a failure. We collect data on 20
similar products that were previously launched. For each product we have recorded whether it was a success or failure, price charged for the product, marketing budget, competition price, and ten other variables.</span></p>
<p>The problem is a binary classification prediction. The N is 20, p is 13.</p>
<p><span style="color: red;">
(c) We are interested in predicting the % change in the USD/Euro
exchange rate in relation to the weekly changes in the world
stock markets. Hence we collect weekly data for all of 2012. For
each week we record the % change in the USD/Euro, the %
change in the US market, the % change in the British market,
and the % change in the German market.</span></p>
<p>The % change problem is a regression prediction with a p of 4 and an N of 52.</p>
<p><span style="color: red;">
3. We now revisit the bias-variance decomposition.</span></p>
<p><span style="color: red;">
(a) Provide a sketch of typical (squared) bias, variance, training error, test error, and Bayes (or irreducible) error curves, on a single plot, as we go from less flexible statistical learning methods
towards more flexible approaches. The x-axis should represent
the amount of flexibility in the method, and the y-axis should
represent the values for each curve. There should be five curves.
Make sure to label each one.</span></p>
<p><img src="https://2.bp.blogspot.com/-bSV25_BnIN8/V4Ko7w4pd3I/AAAAAAAAPqk/AhVPSbql3S4W_vv8AhaCpFVYvAX-rY4LgCKgB/s1600/bias-variance.png" /></p>
<p>X-axis: increasing flexibility and model complexity</p>
<p>Y-axis: increasing Error, Variance, and Bias</p>
<p><span style="color: blue;">Blue</span>: Bias</p>
<p><span style="color: brown;">Brown</span>: Variance</p>
<p><span style="color: green;">Yellow</span>: Training set MSE</p>
<p><span style="color: green;">Green</span>: Testing set MSE</p>
<p>Black: Irreducibile error (Bayes)</p>
<p><span style="color: red;">
(b) Explain why each of the five curves has the shape displayed in
part (a).</span></p>
<p><span style="color: green;">Yellow</span>: As models become more flexible and complex, the training error is reduced, but with diminishing benefit.</p>
<p><span style="color: green;">Green</span>: We often observe a U-shaped error in the holdout training error. This is a combination of the Bias error above the least flexible model and the Variance error from over-fitting the most flexible models and the irreducible error component.</p>
<p><span style="color: blue;">Blue</span>: The bias error component, as observed in the test result</p>
<p><span style="color: brown;">Brown</span>: The variance error component, as observed in the test result</p>
<p>Black: The irreducible error component, as observed in the test result</p>
<p><span style="color: red;">
4. You will now think of some real-life applications for statistical learning.</span></p>
<p><span style="color: red;">
(a) Describe three real-life applications in which classification might
be useful. Describe the response, as well as the predictors. Is the
goal of each application inference or prediction? Explain your
answer.</span></p>
<ul>
<li><p>Infer the causes of expedited freight for a component part. The independent predictors would include country of origin, shipping method, promised lead time, and schedule changes for a year of deliveries.</p></li>
<li><p>Predict customer churn for a learning labs subscription education program. The independent predictors would include monthly payment history, course topics, and web site visits.</p></li>
<li><p>Predict the alphabetic letter of samples of handwriting. The independent predictors would be the pixels of many labeled images.</p></li>
</ul>
<p><span style="color: red;">
(b) Describe three real-life applications in which regression might
be useful. Describe the response, as well as the predictors. Is the
goal of each application inference or prediction? Explain your
answer.</span></p>
<ul>
<li><p>Predict the survival rate of a vehicle component part in use by customers. The response is the proportion of parts still in service, censored. The independent predictors would include engine hours accumulated, region, machine chassis, and type of farm.</p></li>
<li><p>Infer the characteristics of bottles of wine that influence price. The independent predictors would include the vintage year, the type of grape, the region, the color of the bottle, and the length of the story on the label.</p></li>
<li><p>Predict the number of sales conversions per visitor for a web portal store front, given the catalog of products available, the layout parameters of the web site, the colors, and dimensions of the shopping experience.</p></li>
</ul>
<p><span style="color: red;">
(c) Describe three real-life applications in which cluster analysis
might be useful.</span></p>
<ul>
<li><p>Given demographic data on millions of customers and what they buy, build five persona’s for describing the current customer base to a company investor.</p></li>
<li><p>Given IoT operating data from agricultural equipment, build three persona’s for characterizing duty cycles of a fleet.</p></li>
<li><p>Given employee communications transactional data, build three persona’s for better tailoring targeted leadership training.</p></li>
</ul>
<p><span style="color: red;">
5. What are the advantages and disadvantages of a very flexible (versus
a less flexible) approach for regression or classification? Under what
circumstances might a more flexible approach be preferred to a less
flexible approach? When might a less flexible approach be preferred?</span></p>
<p>The very flexible GBMs and Neural Nets require more data, and are often both less interpretable and explainable. Banks and highly regulated entities prefer simple linear models and decision trees so they can explain their management policies in simple terms.</p>
<p><span style="color: red;">
6. Describe the differences between a parametric and a non-parametric
statistical learning approach. What are the advantages of a parametric approach to regression or classification (as opposed to a nonparametric approach)? What are its disadvantages?</span></p>
<p>In any parametric approach we start with an assumption about the functional form and then work towards fitting the data to the closest version of that functional form. On advantage is in explainability, and another is that less data is required to build a useful model. A disadvantage is that the model might never achieve the lowest error rate.</p>
<p><span style="color: red;">
7. The table below provides a training data set containing six observations, three predictors, and one qualitative response variable.</span></p>
<table>
<thead>
<tr class="header">
<th align="left">Obs.</th>
<th align="left">X1</th>
<th align="left">X2</th>
<th align="left">X3</th>
<th align="left">Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">0</td>
<td align="left">3</td>
<td align="left">0</td>
<td align="left">Red</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left">2</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">Red</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">3</td>
<td align="left">Red</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">2</td>
<td align="left">Green</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left">−1</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">Green</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">Red</td>
</tr>
</tbody>
</table>
<p><span style="color: red;">Suppose we wish to use this data set to make a prediction for Y when X1 = X2 = X3 = 0 using K-nearest neighbors.</span></p>
<p><span style="color: red;">(a) Compute the Euclidean distance between each observation and
the test point, X1 = X2 = X3 = 0.</span></p>
<p>Red: sqrt((0-0)^2 + (0-3)^2 + (0-0)^2 )= sqrt(9) = 3</p>
<p>Red: sqrt((0-2)^2 + (0-0)^2 + (0-0)^2 )= sqrt(4) = 2</p>
<p>Red: sqrt((0-0)^2 + (0-1)^2 + (0-3)^2 )= sqrt(10) = 3.162278</p>
<p>Green: sqrt((0-0)^2 + (0-1)^2 + (0-2)^2 )= sqrt(5)= 2.236068</p>
<p>Green: sqrt((0+1)^2 + (0-0)^2 + (0-1)^2 )= sqrt(2) =1.414214</p>
<p>Red: sqrt((0-1)^2 + (0-1)^2 + (0-1)^2 )= sqrt(3)=1.732051</p>
<p><span style="color: red;">(b) What is our prediction with K = 1? Why?</span></p>
<p>For a test set X1=X2=X3=0, this is closest to Green which is at a distance sqrt(2). Therefore the prediction is Green.</p>
<p><span style="color: red;">(c) What is our prediction with K = 3? Why?</span></p>
<p>For a test set X1=X2=X3=0, this is closest to Red (Obs 2), Green(Obs 5) and Red(Obs 6). Thus the prediction will be Red.</p>
<p><span style="color: red;">(d) If the Bayes decision boundary in this problem is highly nonlinear, then would we expect the best value for K to be large or small? Why?</span></p>
<p>Small k values yield a model with lots of detailed curves in the boundary, and likely the lowest irreducible error.</p>
<h4>
<strong>Applied</strong>
</h4>
<p><span style="color: red;">8. This exercise relates to the College data set, which can be found in the file College.csv on the book website.</span></p>
<p><span style="color: red;">(a) Use the read.csv() function to read the data into R. Call the loaded data college. Make sure that you have the directory set to the correct location for the data.</span></p>
<p><span style="color: red;">(b) Look at the data using the View() function. You should notice that the first column is just the name of each university. We don’t really want R to treat this as data. However, it may be handy to have these names for later. Try the following commands:</span></p>
<p><span style="color: red;">(c) i. Use the summary() function to produce a numerical summary
of the variables in the data set.</span></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="exercises.html#cb26-1"></a>college &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://www.statlearning.com/s/College.csv&quot;</span>,</span>
<span id="cb26-2"><a href="exercises.html#cb26-2"></a>                    <span class="dt">show_col_types =</span> <span class="ot">FALSE</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-3"><a href="exercises.html#cb26-3"></a><span class="st">   </span><span class="kw">rename</span>(<span class="dt">college =</span> <span class="st">`</span><span class="dt">...1</span><span class="st">`</span>) </span></code></pre></div>
<pre><code>## New names:
## * `` -&gt; ...1</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="exercises.html#cb28-1"></a><span class="kw">summary</span>(college)</span></code></pre></div>
<pre><code>##    college            Private               Apps           Accept     
##  Length:777         Length:777         Min.   :   81   Min.   :   72  
##  Class :character   Class :character   1st Qu.:  776   1st Qu.:  604  
##  Mode  :character   Mode  :character   Median : 1558   Median : 1110  
##                                        Mean   : 3002   Mean   : 2019  
##                                        3rd Qu.: 3624   3rd Qu.: 2424  
##                                        Max.   :48094   Max.   :26330  
##      Enroll       Top10perc       Top25perc      F.Undergrad   
##  Min.   :  35   Min.   : 1.00   Min.   :  9.0   Min.   :  139  
##  1st Qu.: 242   1st Qu.:15.00   1st Qu.: 41.0   1st Qu.:  992  
##  Median : 434   Median :23.00   Median : 54.0   Median : 1707  
##  Mean   : 780   Mean   :27.56   Mean   : 55.8   Mean   : 3700  
##  3rd Qu.: 902   3rd Qu.:35.00   3rd Qu.: 69.0   3rd Qu.: 4005  
##  Max.   :6392   Max.   :96.00   Max.   :100.0   Max.   :31643  
##   P.Undergrad         Outstate       Room.Board       Books       
##  Min.   :    1.0   Min.   : 2340   Min.   :1780   Min.   :  96.0  
##  1st Qu.:   95.0   1st Qu.: 7320   1st Qu.:3597   1st Qu.: 470.0  
##  Median :  353.0   Median : 9990   Median :4200   Median : 500.0  
##  Mean   :  855.3   Mean   :10441   Mean   :4358   Mean   : 549.4  
##  3rd Qu.:  967.0   3rd Qu.:12925   3rd Qu.:5050   3rd Qu.: 600.0  
##  Max.   :21836.0   Max.   :21700   Max.   :8124   Max.   :2340.0  
##     Personal         PhD            Terminal       S.F.Ratio    
##  Min.   : 250   Min.   :  8.00   Min.   : 24.0   Min.   : 2.50  
##  1st Qu.: 850   1st Qu.: 62.00   1st Qu.: 71.0   1st Qu.:11.50  
##  Median :1200   Median : 75.00   Median : 82.0   Median :13.60  
##  Mean   :1341   Mean   : 72.66   Mean   : 79.7   Mean   :14.09  
##  3rd Qu.:1700   3rd Qu.: 85.00   3rd Qu.: 92.0   3rd Qu.:16.50  
##  Max.   :6800   Max.   :103.00   Max.   :100.0   Max.   :39.80  
##   perc.alumni        Expend        Grad.Rate     
##  Min.   : 0.00   Min.   : 3186   Min.   : 10.00  
##  1st Qu.:13.00   1st Qu.: 6751   1st Qu.: 53.00  
##  Median :21.00   Median : 8377   Median : 65.00  
##  Mean   :22.74   Mean   : 9660   Mean   : 65.46  
##  3rd Qu.:31.00   3rd Qu.:10830   3rd Qu.: 78.00  
##  Max.   :64.00   Max.   :56233   Max.   :118.00</code></pre>
<p><span style="color: red;">ii. Use the pairs() function to produce a scatterplot matrix of
the first ten columns or variables of the data. Recall that you can reference the first ten columns of a matrix A using A[,1:10].</span></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="exercises.html#cb30-1"></a><span class="co"># pairs(college[,3:12])</span></span>
<span id="cb30-2"><a href="exercises.html#cb30-2"></a></span>
<span id="cb30-3"><a href="exercises.html#cb30-3"></a>GGally<span class="op">::</span><span class="kw">ggpairs</span>(college[,<span class="dv">2</span><span class="op">:</span><span class="dv">11</span>],</span>
<span id="cb30-4"><a href="exercises.html#cb30-4"></a>                <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">color =</span> Private),</span>
<span id="cb30-5"><a href="exercises.html#cb30-5"></a>                <span class="dt">progress =</span> <span class="ot">FALSE</span>,</span>
<span id="cb30-6"><a href="exercises.html#cb30-6"></a>                <span class="dt">lower =</span> <span class="kw">list</span>(<span class="dt">combo =</span> GGally<span class="op">::</span><span class="kw">wrap</span>(<span class="st">&quot;facethist&quot;</span>,  </span>
<span id="cb30-7"><a href="exercises.html#cb30-7"></a><span class="dt">bins =</span> <span class="dv">40</span>))) <span class="op">+</span></span>
<span id="cb30-8"><a href="exercises.html#cb30-8"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb30-9"><a href="exercises.html#cb30-9"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.grid =</span> <span class="kw">element_blank</span>()) <span class="op">+</span></span>
<span id="cb30-10"><a href="exercises.html#cb30-10"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">caption =</span> <span class="st">&quot;Source: ISLR2::College | Ten numeric features&quot;</span>) </span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-5-1.png" width="1152" /></p>
<p><span style="color: red;">iii. Use the plot() function to produce side-by-side boxplots of
Outstate versus Private.</span></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="exercises.html#cb32-1"></a><span class="co"># plot( college$Private, college$Outstate )</span></span>
<span id="cb32-2"><a href="exercises.html#cb32-2"></a></span>
<span id="cb32-3"><a href="exercises.html#cb32-3"></a>college <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb32-4"><a href="exercises.html#cb32-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(Private, Outstate)) <span class="op">+</span></span>
<span id="cb32-5"><a href="exercises.html#cb32-5"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb32-6"><a href="exercises.html#cb32-6"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb32-7"><a href="exercises.html#cb32-7"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.grid =</span> <span class="kw">element_blank</span>()) <span class="op">+</span></span>
<span id="cb32-8"><a href="exercises.html#cb32-8"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">caption =</span> <span class="st">&quot;Source: ISLR2::College&quot;</span>) </span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p><span style="color: red;">iv. Create a new qualitative variable, called Elite, by binning
the <code>Top10perc</code> variable. We are going to divide universities into two groups based on whether or not the proportion of students coming from the top 10 % of their high school
classes exceeds 50 %.</span></p>
<p><span style="color: red;">Use the summary() function to see how many elite universities there are.</span></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="exercises.html#cb33-1"></a><span class="co"># Elite &lt;- rep(&quot;No&quot;, nrow(college))</span></span>
<span id="cb33-2"><a href="exercises.html#cb33-2"></a><span class="co"># Elite[college$Top10perc &gt; 50] &lt;- &quot; Yes &quot;</span></span>
<span id="cb33-3"><a href="exercises.html#cb33-3"></a><span class="co"># Elite &lt;- as.factor(Elite)</span></span>
<span id="cb33-4"><a href="exercises.html#cb33-4"></a><span class="co"># college &lt;- data.frame(college , Elite)</span></span>
<span id="cb33-5"><a href="exercises.html#cb33-5"></a></span>
<span id="cb33-6"><a href="exercises.html#cb33-6"></a>college &lt;-<span class="st"> </span>college <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb33-7"><a href="exercises.html#cb33-7"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Elite =</span> <span class="kw">as_factor</span>(<span class="kw">if_else</span>(Top10perc <span class="op">&gt;</span><span class="st"> </span><span class="dv">50</span>, <span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>)))</span>
<span id="cb33-8"><a href="exercises.html#cb33-8"></a></span>
<span id="cb33-9"><a href="exercises.html#cb33-9"></a><span class="kw">summary</span>(college<span class="op">$</span>Elite)</span></code></pre></div>
<pre><code>##  No Yes 
## 699  78</code></pre>
<p><span style="color: red;">Now use the plot() function to produce side-by-side boxplots of Outstate versus Elite.</span></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="exercises.html#cb35-1"></a><span class="co">#plot( college$Elite, college$Outstate )</span></span>
<span id="cb35-2"><a href="exercises.html#cb35-2"></a></span>
<span id="cb35-3"><a href="exercises.html#cb35-3"></a>college <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb35-4"><a href="exercises.html#cb35-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(Elite, Outstate)) <span class="op">+</span></span>
<span id="cb35-5"><a href="exercises.html#cb35-5"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb35-6"><a href="exercises.html#cb35-6"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb35-7"><a href="exercises.html#cb35-7"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.grid =</span> <span class="kw">element_blank</span>()) <span class="op">+</span></span>
<span id="cb35-8"><a href="exercises.html#cb35-8"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">caption =</span> <span class="st">&quot;Source: ISLR2::College&quot;</span>) </span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p><span style="color: red;">v. Use the hist() function to produce some histograms with
differing numbers of bins for a few of the quantitative variables. You may find the command par(mfrow = c(2, 2)) useful: it will divide the print window into four regions so
that four plots can be made simultaneously. Modifying the arguments to this function will divide the screen in other ways.</span></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="exercises.html#cb36-1"></a>college <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb36-2"><a href="exercises.html#cb36-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(Enroll, <span class="dt">fill =</span> Private)) <span class="op">+</span></span>
<span id="cb36-3"><a href="exercises.html#cb36-3"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">40</span>) <span class="op">+</span><span class="st">  </span></span>
<span id="cb36-4"><a href="exercises.html#cb36-4"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb36-5"><a href="exercises.html#cb36-5"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.grid =</span> <span class="kw">element_blank</span>()) <span class="op">+</span></span>
<span id="cb36-6"><a href="exercises.html#cb36-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">caption =</span> <span class="st">&quot;Source: ISLR2::College&quot;</span>) </span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p><span style="color: red;">vi. Continue exploring the data, and provide a brief summary
of what you discover.</span></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="exercises.html#cb37-1"></a>GGally<span class="op">::</span><span class="kw">ggpairs</span>(<span class="kw">bind_cols</span>(college[,<span class="dv">2</span>],college[,<span class="dv">12</span><span class="op">:</span><span class="dv">18</span>]),</span>
<span id="cb37-2"><a href="exercises.html#cb37-2"></a>                <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">color =</span> Private),</span>
<span id="cb37-3"><a href="exercises.html#cb37-3"></a>                <span class="dt">progress =</span> <span class="ot">FALSE</span>,</span>
<span id="cb37-4"><a href="exercises.html#cb37-4"></a>                <span class="dt">lower =</span> <span class="kw">list</span>(<span class="dt">combo =</span> GGally<span class="op">::</span><span class="kw">wrap</span>(<span class="st">&quot;facethist&quot;</span>,  </span>
<span id="cb37-5"><a href="exercises.html#cb37-5"></a><span class="dt">bins =</span> <span class="dv">40</span>))) <span class="op">+</span></span>
<span id="cb37-6"><a href="exercises.html#cb37-6"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb37-7"><a href="exercises.html#cb37-7"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.grid =</span> <span class="kw">element_blank</span>()) <span class="op">+</span></span>
<span id="cb37-8"><a href="exercises.html#cb37-8"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">caption =</span> <span class="st">&quot;Source: ISLR2::College | Ten numeric features&quot;</span>) </span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-10-1.png" width="1152" /></p>
<p>The public institutions in this dataset enroll more undergraduates, while the private ones have more pursuing terminal degrees in their fields.</p>
<p><span style="color: red;">9. This exercise involves the Auto data set studied in the lab. Make sure that the missing values have been removed from the data.
(a) Which of the predictors are quantitative, and which are qualitative?</span></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="exercises.html#cb38-1"></a>Auto &lt;-<span class="st"> </span>ISLR2<span class="op">::</span>Auto <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb38-2"><a href="exercises.html#cb38-2"></a><span class="st">  </span>drop_na <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb38-3"><a href="exercises.html#cb38-3"></a><span class="st">  </span><span class="kw">tibble</span>()</span>
<span id="cb38-4"><a href="exercises.html#cb38-4"></a></span>
<span id="cb38-5"><a href="exercises.html#cb38-5"></a><span class="co"># summary(Auto)</span></span>
<span id="cb38-6"><a href="exercises.html#cb38-6"></a></span>
<span id="cb38-7"><a href="exercises.html#cb38-7"></a>skimr<span class="op">::</span><span class="kw">skim</span>(Auto)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-11">Table 2.1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Auto</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">392</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">9</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">factor</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">8</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="left">ordered</th>
<th align="right">n_unique</th>
<th align="left">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">name</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">301</td>
<td align="left">amc: 5, for: 5, toy: 5, amc: 4</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">23.45</td>
<td align="right">7.81</td>
<td align="right">9</td>
<td align="right">17.00</td>
<td align="right">22.75</td>
<td align="right">29.00</td>
<td align="right">46.6</td>
<td align="left">▆▇▆▃▁</td>
</tr>
<tr class="even">
<td align="left">cylinders</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5.47</td>
<td align="right">1.71</td>
<td align="right">3</td>
<td align="right">4.00</td>
<td align="right">4.00</td>
<td align="right">8.00</td>
<td align="right">8.0</td>
<td align="left">▇▁▃▁▅</td>
</tr>
<tr class="odd">
<td align="left">displacement</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">194.41</td>
<td align="right">104.64</td>
<td align="right">68</td>
<td align="right">105.00</td>
<td align="right">151.00</td>
<td align="right">275.75</td>
<td align="right">455.0</td>
<td align="left">▇▂▂▃▁</td>
</tr>
<tr class="even">
<td align="left">horsepower</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">104.47</td>
<td align="right">38.49</td>
<td align="right">46</td>
<td align="right">75.00</td>
<td align="right">93.50</td>
<td align="right">126.00</td>
<td align="right">230.0</td>
<td align="left">▆▇▃▁▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2977.58</td>
<td align="right">849.40</td>
<td align="right">1613</td>
<td align="right">2225.25</td>
<td align="right">2803.50</td>
<td align="right">3614.75</td>
<td align="right">5140.0</td>
<td align="left">▇▇▅▅▂</td>
</tr>
<tr class="even">
<td align="left">acceleration</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">15.54</td>
<td align="right">2.76</td>
<td align="right">8</td>
<td align="right">13.78</td>
<td align="right">15.50</td>
<td align="right">17.02</td>
<td align="right">24.8</td>
<td align="left">▁▆▇▂▁</td>
</tr>
<tr class="odd">
<td align="left">year</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">75.98</td>
<td align="right">3.68</td>
<td align="right">70</td>
<td align="right">73.00</td>
<td align="right">76.00</td>
<td align="right">79.00</td>
<td align="right">82.0</td>
<td align="left">▇▆▇▆▇</td>
</tr>
<tr class="even">
<td align="left">origin</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1.58</td>
<td align="right">0.81</td>
<td align="right">1</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">2.00</td>
<td align="right">3.0</td>
<td align="left">▇▁▂▁▂</td>
</tr>
</tbody>
</table>
<p>Quantitative: mpg, cylinders, displacement, horsepower, weight, acceleration, year, origin</p>
<p>Qualitative: name</p>
<p><span style="color: red;">(b) What is the range of each quantitative predictor? You can answer this using the range() function. range()</span></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="exercises.html#cb39-1"></a>Auto <span class="op">%&gt;%</span></span>
<span id="cb39-2"><a href="exercises.html#cb39-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="kw">where</span>(is.numeric)) <span class="op">%&gt;%</span></span>
<span id="cb39-3"><a href="exercises.html#cb39-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), range)) <span class="op">%&gt;%</span></span>
<span id="cb39-4"><a href="exercises.html#cb39-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">level =</span> <span class="kw">c</span>(<span class="st">&quot;min&quot;</span>, <span class="st">&quot;max&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb39-5"><a href="exercises.html#cb39-5"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="op">-</span>level,</span>
<span id="cb39-6"><a href="exercises.html#cb39-6"></a>               <span class="dt">names_to =</span> <span class="st">&quot;metric&quot;</span>,</span>
<span id="cb39-7"><a href="exercises.html#cb39-7"></a>               <span class="dt">values_to =</span> <span class="st">&quot;value&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb39-8"><a href="exercises.html#cb39-8"></a><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> level,</span>
<span id="cb39-9"><a href="exercises.html#cb39-9"></a>              <span class="dt">values_from =</span> value)</span></code></pre></div>
<pre><code>## # A tibble: 8 × 3
##   metric         min    max
##   &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;
## 1 mpg              9   46.6
## 2 cylinders        3    8  
## 3 displacement    68  455  
## 4 horsepower      46  230  
## 5 weight        1613 5140  
## 6 acceleration     8   24.8
## 7 year            70   82  
## 8 origin           1    3</code></pre>
<p><span style="color: red;">(c) What is the mean and standard deviation of each quantitative predictor?</span></p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="exercises.html#cb41-1"></a>Auto <span class="op">%&gt;%</span></span>
<span id="cb41-2"><a href="exercises.html#cb41-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="kw">where</span>(is.numeric)) <span class="op">%&gt;%</span></span>
<span id="cb41-3"><a href="exercises.html#cb41-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(),</span>
<span id="cb41-4"><a href="exercises.html#cb41-4"></a>                                                                       <span class="dt">values_to =</span> <span class="st">&quot;mean&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 8 × 2
##   name            mean
##   &lt;chr&gt;          &lt;dbl&gt;
## 1 mpg            23.4 
## 2 cylinders       5.47
## 3 displacement  194.  
## 4 horsepower    104.  
## 5 weight       2978.  
## 6 acceleration   15.5 
## 7 year           76.0 
## 8 origin          1.58</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="exercises.html#cb43-1"></a>Auto <span class="op">%&gt;%</span></span>
<span id="cb43-2"><a href="exercises.html#cb43-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="kw">where</span>(is.numeric)) <span class="op">%&gt;%</span></span>
<span id="cb43-3"><a href="exercises.html#cb43-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), sd, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(),</span>
<span id="cb43-4"><a href="exercises.html#cb43-4"></a>                                                                     <span class="dt">values_to =</span> <span class="st">&quot;sd&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 8 × 2
##   name              sd
##   &lt;chr&gt;          &lt;dbl&gt;
## 1 mpg            7.81 
## 2 cylinders      1.71 
## 3 displacement 105.   
## 4 horsepower    38.5  
## 5 weight       849.   
## 6 acceleration   2.76 
## 7 year           3.68 
## 8 origin         0.806</code></pre>
<p><span style="color: red;">(d) Now remove the 10th through 85th observations. What is the range, mean, and standard deviation of each predictor in the subset of the data that remains?</span></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="exercises.html#cb45-1"></a>Auto[<span class="op">-</span><span class="kw">c</span>(<span class="dv">10</span><span class="op">:</span><span class="dv">85</span>), ] <span class="op">%&gt;%</span></span>
<span id="cb45-2"><a href="exercises.html#cb45-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="kw">where</span>(is.numeric)) <span class="op">%&gt;%</span></span>
<span id="cb45-3"><a href="exercises.html#cb45-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(),</span>
<span id="cb45-4"><a href="exercises.html#cb45-4"></a>                   range, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) <span class="op">%&gt;%</span></span>
<span id="cb45-5"><a href="exercises.html#cb45-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">level =</span> <span class="kw">c</span>(<span class="st">&quot;min&quot;</span>, <span class="st">&quot;max&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb45-6"><a href="exercises.html#cb45-6"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="op">-</span>level,</span>
<span id="cb45-7"><a href="exercises.html#cb45-7"></a>               <span class="dt">names_to =</span> <span class="st">&quot;metric&quot;</span>,</span>
<span id="cb45-8"><a href="exercises.html#cb45-8"></a>               <span class="dt">values_to =</span> <span class="st">&quot;value&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb45-9"><a href="exercises.html#cb45-9"></a><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> level,</span>
<span id="cb45-10"><a href="exercises.html#cb45-10"></a>              <span class="dt">values_from =</span> value)</span></code></pre></div>
<pre><code>## # A tibble: 8 × 3
##   metric          min    max
##   &lt;chr&gt;         &lt;dbl&gt;  &lt;dbl&gt;
## 1 mpg            11     46.6
## 2 cylinders       3      8  
## 3 displacement   68    455  
## 4 horsepower     46    230  
## 5 weight       1649   4997  
## 6 acceleration    8.5   24.8
## 7 year           70     82  
## 8 origin          1      3</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="exercises.html#cb47-1"></a>Auto[<span class="op">-</span><span class="kw">c</span>(<span class="dv">10</span><span class="op">:</span><span class="dv">85</span>), ] <span class="op">%&gt;%</span></span>
<span id="cb47-2"><a href="exercises.html#cb47-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="kw">where</span>(is.numeric)) <span class="op">%&gt;%</span></span>
<span id="cb47-3"><a href="exercises.html#cb47-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) <span class="op">%&gt;%</span></span>
<span id="cb47-4"><a href="exercises.html#cb47-4"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(),</span>
<span id="cb47-5"><a href="exercises.html#cb47-5"></a>               <span class="dt">values_to =</span> <span class="st">&quot;mean&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 8 × 2
##   name            mean
##   &lt;chr&gt;          &lt;dbl&gt;
## 1 mpg            24.4 
## 2 cylinders       5.37
## 3 displacement  187.  
## 4 horsepower    101.  
## 5 weight       2936.  
## 6 acceleration   15.7 
## 7 year           77.1 
## 8 origin          1.60</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="exercises.html#cb49-1"></a>Auto[<span class="op">-</span><span class="kw">c</span>(<span class="dv">10</span><span class="op">:</span><span class="dv">85</span>), ] <span class="op">%&gt;%</span></span>
<span id="cb49-2"><a href="exercises.html#cb49-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="kw">where</span>(is.numeric)) <span class="op">%&gt;%</span></span>
<span id="cb49-3"><a href="exercises.html#cb49-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), sd, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) <span class="op">%&gt;%</span></span>
<span id="cb49-4"><a href="exercises.html#cb49-4"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(),</span>
<span id="cb49-5"><a href="exercises.html#cb49-5"></a>               <span class="dt">values_to =</span> <span class="st">&quot;sd&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 8 × 2
##   name              sd
##   &lt;chr&gt;          &lt;dbl&gt;
## 1 mpg            7.87 
## 2 cylinders      1.65 
## 3 displacement  99.7  
## 4 horsepower    35.7  
## 5 weight       811.   
## 6 acceleration   2.69 
## 7 year           3.11 
## 8 origin         0.820</code></pre>
<p><span style="color: red;">(e) Using the full data set, investigate the predictors graphically, using scatterplots or other tools of your choice. Create some plots highlighting the relationships among the predictors. Comment on your findings.</span></p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="exercises.html#cb51-1"></a>GGally<span class="op">::</span><span class="kw">ggpairs</span>(<span class="kw">select</span>(Auto, <span class="op">-</span>name),</span>
<span id="cb51-2"><a href="exercises.html#cb51-2"></a>                <span class="dt">progress =</span> <span class="ot">FALSE</span>,</span>
<span id="cb51-3"><a href="exercises.html#cb51-3"></a>                <span class="dt">lower =</span> <span class="kw">list</span>(<span class="dt">combo =</span> GGally<span class="op">::</span><span class="kw">wrap</span>(<span class="st">&quot;facethist&quot;</span>,  </span>
<span id="cb51-4"><a href="exercises.html#cb51-4"></a><span class="dt">bins =</span> <span class="dv">40</span>)))</span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-15-1.png" width="1152" /></p>
<p><code>displacement</code> appears to have a positive relationship with <code>horsepower</code></p>
<p><code>mpg</code> has a negative, nonlinear relationship with <code>displacement</code></p>
<p><span style="color: red;">(f) Suppose that we wish to predict gas mileage (mpg) on the basis of the other variables. Do your plots suggest that any of the other variables might be useful in predicting mpg? Justify your answer.</span></p>
<p>Yes, a predictive model is certainly possible with this data set.</p>
<p><span style="color: red;">2.4 Exercises 57
10. This exercise involves the Boston housing data set. (a) To begin, load in the Boston data set. The Boston data set is part of the ISLR2 library.</span></p>
<p><span style="color: red;">How many rows are in this data set?</span></p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="exercises.html#cb52-1"></a><span class="kw">nrow</span>(ISLR2<span class="op">::</span>Boston)</span></code></pre></div>
<pre><code>## [1] 506</code></pre>
<p><span style="color: red;">How many columns?</span></p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="exercises.html#cb54-1"></a><span class="kw">ncol</span>(ISLR2<span class="op">::</span>Boston)</span></code></pre></div>
<pre><code>## [1] 13</code></pre>
<p><span style="color: red;">What do the rows and columns represent?</span></p>
<p>These are housing sale values <code>medv</code> and the characteristics of 506 suburbs of Boston.</p>
<p><span style="color: red;">(b) Make some pairwise scatterplots of the predictors (columns) in this data set. Describe your findings.</span></p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="exercises.html#cb56-1"></a>GGally<span class="op">::</span><span class="kw">ggpairs</span>(ISLR2<span class="op">::</span>Boston,</span>
<span id="cb56-2"><a href="exercises.html#cb56-2"></a>                <span class="dt">progress =</span> <span class="ot">FALSE</span>,</span>
<span id="cb56-3"><a href="exercises.html#cb56-3"></a>                <span class="dt">lower =</span> <span class="kw">list</span>(<span class="dt">combo =</span> GGally<span class="op">::</span><span class="kw">wrap</span>(<span class="st">&quot;facethist&quot;</span>,  </span>
<span id="cb56-4"><a href="exercises.html#cb56-4"></a><span class="dt">bins =</span> <span class="dv">40</span>)))</span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-18-1.png" width="1152" /></p>
<p><code>medv</code> is reduced with higher <code>lstat</code></p>
<p><code>medv</code> increases with <code>rm</code></p>
<p><span style="color: red;">(c) Are any of the predictors associated with per capita crime rate? If so, explain the relationship.</span></p>
<p>Yes, <code>rad</code> highway access moderately at 0.626. Crime is highest at low <code>rad</code>, drops quickly, and then increase somewhat at high <code>rad</code>.</p>
<p><span style="color: red;">(d) Do any of the census tracts of Boston appear to have particularly high crime rates? Tax rates? Pupil-teacher ratios? Comment on the range of each predictor</span></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="exercises.html#cb57-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb57-2"><a href="exercises.html#cb57-2"></a><span class="st">  </span><span class="kw">slice_max</span>(crim, <span class="dt">n =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##      crim zn indus chas   nox    rm   age    dis rad tax ptratio lstat medv
## 1 88.9762  0  18.1    0 0.671 6.968  91.9 1.4165  24 666    20.2 17.21 10.4
## 2 73.5341  0  18.1    0 0.679 5.957 100.0 1.8026  24 666    20.2 20.62  8.8
## 3 67.9208  0  18.1    0 0.693 5.683 100.0 1.4254  24 666    20.2 22.98  5.0</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="exercises.html#cb59-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb59-2"><a href="exercises.html#cb59-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(crim)) <span class="op">+</span></span>
<span id="cb59-3"><a href="exercises.html#cb59-3"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>)</span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Yes, the median crime rate <code>crim</code> is very low, at only 0.257. This feature is heavily skewed right. The range runs from 0.00637 to 89.0.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="exercises.html#cb60-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb60-2"><a href="exercises.html#cb60-2"></a><span class="st">  </span><span class="kw">slice_max</span>(tax, <span class="dt">n =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##      crim zn indus chas   nox    rm  age    dis rad tax ptratio lstat medv
## 1 0.15086  0 27.74    0 0.609 5.454 92.7 1.8209   4 711    20.1 18.06 15.2
## 2 0.18337  0 27.74    0 0.609 5.414 98.3 1.7554   4 711    20.1 23.97  7.0
## 3 0.20746  0 27.74    0 0.609 5.093 98.0 1.8226   4 711    20.1 29.68  8.1
## 4 0.10574  0 27.74    0 0.609 5.983 98.8 1.8681   4 711    20.1 18.07 13.6
## 5 0.11132  0 27.74    0 0.609 5.983 83.5 2.1099   4 711    20.1 13.35 20.1</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="exercises.html#cb62-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb62-2"><a href="exercises.html#cb62-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(tax)) <span class="op">+</span></span>
<span id="cb62-3"><a href="exercises.html#cb62-3"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>)</span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Yes, median full value tax rates range from 169k to 711k. The distribution across suburbs is also not even.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="exercises.html#cb63-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb63-2"><a href="exercises.html#cb63-2"></a><span class="st">  </span><span class="kw">slice_min</span>(ptratio , <span class="dt">n =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##      crim zn indus chas   nox    rm  age   dis rad tax ptratio lstat medv
## 1 0.04011 80  1.52    0 0.404 7.287 34.1 7.309   2 329    12.6  4.08 33.3
## 2 0.04666 80  1.52    0 0.404 7.107 36.6 7.309   2 329    12.6  8.61 30.3
## 3 0.03768 80  1.52    0 0.404 7.274 38.3 7.309   2 329    12.6  6.62 34.6</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="exercises.html#cb65-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb65-2"><a href="exercises.html#cb65-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(ptratio)) <span class="op">+</span></span>
<span id="cb65-3"><a href="exercises.html#cb65-3"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>)</span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>The <code>ptratio</code> is skewed left, with the bulk of the suburbs at the high end of the range from 2.16 to 38.</p>
<p><span style="color: red;">(e) How many of the census tracts in this data set bound the Charles river?</span></p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="exercises.html#cb66-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb66-2"><a href="exercises.html#cb66-2"></a><span class="st">  </span><span class="kw">count</span>(chas <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>##   chas == 1   n
## 1     FALSE 471
## 2      TRUE  35</code></pre>
<p>35 suburbs bound the Charles River</p>
<p><span style="color: red;">(f) What is the median pupil-teacher ratio among the towns in this data set?</span></p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="exercises.html#cb68-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb68-2"><a href="exercises.html#cb68-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">ptratio_median =</span> <span class="kw">median</span>(ptratio))</span></code></pre></div>
<pre><code>##   ptratio_median
## 1          19.05</code></pre>
<p><span style="color: red;">(g) Which census tract of Boston has lowest median value of owner occupied homes?</span></p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="exercises.html#cb70-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb70-2"><a href="exercises.html#cb70-2"></a><span class="st">  </span><span class="kw">add_rowindex</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb70-3"><a href="exercises.html#cb70-3"></a><span class="st">  </span><span class="kw">select</span>(.row, medv) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb70-4"><a href="exercises.html#cb70-4"></a><span class="st">  </span><span class="kw">filter</span>(medv <span class="op">==</span><span class="st"> </span><span class="kw">min</span>(medv))</span></code></pre></div>
<pre><code>##   .row medv
## 1  399    5
## 2  406    5</code></pre>
<p>Rows 399 and 406.</p>
<p><span style="color: red;">What are the values of the other predictors for that census tract, and how do those values compare to the overall ranges for those predictors? Comment on your findings.</span></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="exercises.html#cb72-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span></span>
<span id="cb72-2"><a href="exercises.html#cb72-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">bottom_tracts =</span></span>
<span id="cb72-3"><a href="exercises.html#cb72-3"></a>           <span class="kw">if_else</span>(medv <span class="op">==</span><span class="st"> </span><span class="kw">min</span>(medv),</span>
<span id="cb72-4"><a href="exercises.html#cb72-4"></a>                   <span class="st">&quot;Bottom&quot;</span>,</span>
<span id="cb72-5"><a href="exercises.html#cb72-5"></a>                   <span class="ot">NA_character_</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb72-6"><a href="exercises.html#cb72-6"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="op">-</span><span class="kw">c</span>(bottom_tracts, medv)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb72-7"><a href="exercises.html#cb72-7"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(value, medv, <span class="dt">color =</span> bottom_tracts)) <span class="op">+</span></span>
<span id="cb72-8"><a href="exercises.html#cb72-8"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb72-9"><a href="exercises.html#cb72-9"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="kw">vars</span>(name),</span>
<span id="cb72-10"><a href="exercises.html#cb72-10"></a>             <span class="dt">scales =</span> <span class="st">&quot;free_x&quot;</span>) <span class="op">+</span></span>
<span id="cb72-11"><a href="exercises.html#cb72-11"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb72-12"><a href="exercises.html#cb72-12"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">strip.placement =</span> <span class="st">&quot;outside&quot;</span>,</span>
<span id="cb72-13"><a href="exercises.html#cb72-13"></a>        <span class="dt">panel.grid =</span> <span class="kw">element_blank</span>(),</span>
<span id="cb72-14"><a href="exercises.html#cb72-14"></a>        <span class="dt">strip.background =</span> <span class="kw">element_blank</span>()) <span class="op">+</span></span>
<span id="cb72-15"><a href="exercises.html#cb72-15"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">caption =</span> <span class="st">&quot;Source: ISLR2::Boston | Lowest Median Home Value Suburbs&quot;</span>,</span>
<span id="cb72-16"><a href="exercises.html#cb72-16"></a>       <span class="dt">color =</span> <span class="ot">NULL</span>)</span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p><span style="color: red;">The lowest median value suburbs of Boston are the oldest, they have higher crime than most, they are close to empoyment centers, they are related to industry, they have high taxes, and a low <code>zn</code> proportion of large lots zoned.</span></p>
<p><span style="color: red;">(h) In this data set, how many of the census tracts average more than seven rooms per dwelling? More than eight rooms per dwelling? Comment on the census tracts that average more than eight rooms per dwelling.</span></p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="exercises.html#cb73-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb73-2"><a href="exercises.html#cb73-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">room_state =</span> <span class="kw">case_when</span>(</span>
<span id="cb73-3"><a href="exercises.html#cb73-3"></a>    rm <span class="op">&gt;</span><span class="st"> </span><span class="dv">8</span> <span class="op">~</span><span class="st"> &quot;eight_plus&quot;</span>,</span>
<span id="cb73-4"><a href="exercises.html#cb73-4"></a>    rm <span class="op">&gt;</span><span class="st"> </span><span class="dv">7</span> <span class="op">~</span><span class="st"> &quot;seven_to_eight&quot;</span>,</span>
<span id="cb73-5"><a href="exercises.html#cb73-5"></a>    <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">NA_character_</span></span>
<span id="cb73-6"><a href="exercises.html#cb73-6"></a>  )) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb73-7"><a href="exercises.html#cb73-7"></a><span class="st">  </span><span class="kw">count</span>(room_state)</span></code></pre></div>
<pre><code>##       room_state   n
## 1     eight_plus  13
## 2 seven_to_eight  51
## 3           &lt;NA&gt; 442</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="exercises.html#cb75-1"></a>ISLR2<span class="op">::</span>Boston <span class="op">%&gt;%</span></span>
<span id="cb75-2"><a href="exercises.html#cb75-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">room_state =</span> <span class="kw">case_when</span>(</span>
<span id="cb75-3"><a href="exercises.html#cb75-3"></a>    rm <span class="op">&gt;</span><span class="st"> </span><span class="dv">8</span> <span class="op">~</span><span class="st"> &quot;eight_plus&quot;</span>,</span>
<span id="cb75-4"><a href="exercises.html#cb75-4"></a>    rm <span class="op">&gt;</span><span class="st"> </span><span class="dv">7</span> <span class="op">~</span><span class="st"> &quot;seven_to_eight&quot;</span>,</span>
<span id="cb75-5"><a href="exercises.html#cb75-5"></a>    <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">NA_character_</span></span>
<span id="cb75-6"><a href="exercises.html#cb75-6"></a>  )) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb75-7"><a href="exercises.html#cb75-7"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="op">-</span><span class="kw">c</span>(room_state, medv)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb75-8"><a href="exercises.html#cb75-8"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(value, medv, <span class="dt">color =</span> room_state)) <span class="op">+</span></span>
<span id="cb75-9"><a href="exercises.html#cb75-9"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">shape =</span> <span class="dv">21</span>, <span class="dt">alpha =</span> <span class="fl">0.7</span>) <span class="op">+</span></span>
<span id="cb75-10"><a href="exercises.html#cb75-10"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="kw">vars</span>(name),</span>
<span id="cb75-11"><a href="exercises.html#cb75-11"></a>             <span class="dt">scales =</span> <span class="st">&quot;free_x&quot;</span>) <span class="op">+</span></span>
<span id="cb75-12"><a href="exercises.html#cb75-12"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb75-13"><a href="exercises.html#cb75-13"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">strip.placement =</span> <span class="st">&quot;outside&quot;</span>,</span>
<span id="cb75-14"><a href="exercises.html#cb75-14"></a>        <span class="dt">panel.grid =</span> <span class="kw">element_blank</span>(),</span>
<span id="cb75-15"><a href="exercises.html#cb75-15"></a>        <span class="dt">strip.background =</span> <span class="kw">element_blank</span>()) <span class="op">+</span></span>
<span id="cb75-16"><a href="exercises.html#cb75-16"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">caption =</span> <span class="st">&quot;Source: ISLR2::Boston | More than 8 rooms per dwelling&quot;</span>,</span>
<span id="cb75-17"><a href="exercises.html#cb75-17"></a>       <span class="dt">color =</span> <span class="ot">NULL</span>)</span></code></pre></div>
<p><img src="bookclub-islr_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Again, the oldest homes have more than 8 rooms per dwelling. They have the lowest tax assessments and a low proportion of non-retail business acres per town.</p>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="assessing-model-accuracy.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="meeting-videos-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/r4ds/bookclub-islr/edit/main/02.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
